config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/tasks/:id/confirm', to: 'tasks#confirm', as: 'confirm'
  devise_for :users
  resources  :tasks 
  root to: redirect('tasks')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :users
    scope :user_id, -> (user_id) { where user_id: user_id }
    scope :status, -> (status) { where status: status }
    scope :priority, -> (priority) { where priority: priority }
    scope :due_date, -> (due_date) { where due_date: due_date }
    scope :starts_with, -> (name) { where("name like ?", "#{name}%")}
    scope :today, -> { where(:due_date => Time.now.beginning_of_day..Time.now.end_of_day) }
    scope :week, -> { where(:due_date => Time.now.beginning_of_week..Time.now.end_of_week) }
    scope :month, -> { where(:due_date => Time.now.beginning_of_month..Time.now.end_of_month) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :tasks, required: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    #member_signed_in?
    #current_member
    #member_session
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    #has_scope :today, type: :boolean
    #has_scope :week, type: :boolean
    #has_scope :month, type: :boolean

    def index
        @task = Task.where("user_id =?", current_user.id).or(Task.where("created_by =?" , current_user.id )).order(due_date: :asc)
        @task = @task.today() if params[:today].present?
        @task = @task.week() if params[:week].present?
        @task = @task.month() if params[:month].present?
        @task = @task.status(params[:status]) if params[:status].present?
        @task = @task.priority(params[:priority]) if params[:priority].present?
        @task = @task.due_date(params[:due_date]) if params[:due_date].present?
        @task = @task.starts_with(params[:starts_with]) if params[:starts_with].present?
       
        
    end
   
    def new
        @task = Task.new
        @user = User.all
       
    end

    def create
        @task = Task.new(task_params)
        @task.created_by =  current_user.id
        
        @task.save
        redirect_to @task
    end

    def show
        @task = Task.find(params[:id]) 
    end

    def edit
        @task =  Task.find(params[:id]) 
        @user = User.all
    end

    def confirm
        @task =  Task.find(params[:id]) 
        @user = User.all
    end

    def update
        @task = Task.find(params[:id])
        
         @task.update(task_params)
         redirect_to @task
        
    end

    def destroy
        @task =  Task.find(params[:id])
        @task.destroy
    end

    
    

    private
    def task_params
        params.require(:task).permit(:name, :description, :status, :priority, :created_date, :due_date, :user_id,:created_by )
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Taskapp
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css", :rel => "stylesheet"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} TodoApp
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            - if user_signed_in?
              %li
                %a{:href =>"/tasks"}MyTask
              %li
                %a{:href =>"/tasks?today=true"}OnToday
              %li
                %a{:href =>"/tasks?week=true"}OnThisWeek
              %li
                %a{:href =>"/tasks?month=true"}OnThisMonth
         
          %p.navbar-text.pull-right
            - if user_signed_in?
              = succeed "." do
                %strong= current_user.email
              = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
              |
              \#{link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
            - else
              = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
              |
              \#{link_to "Login", new_user_session_path, :class => 'navbar-link'}
    .container
      = yield
    
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"}
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"}
    

app/views/tasks/_confirmform.html.haml
.container
.row
.col-md-12.form
  = form_for @task do |f|
    - if @task.errors.any?
      #error_explanation
        %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
        %ul
          - @task.errors.full_messages.each do |message|
            %li= message

    .field.form-group.col-sm-6
      = f.label :name
      = f.text_field :name,class:'form-control',readonly: true
    .field.form-group.col-sm-6
      = f.label :description
      = f.text_area :description,class:'form-control',readonly: true
    .field.form-group.col-sm-6
      = f.label :status
      = f.select :status, options_for_select([['undone', 0], ['done', 1]], params[:status]),{prompt: true, selected: :status}, {required: 'true', autofocus: 'true', class: 'form-control'}
    .field.form-group.col-sm-6
      = f.label :priority
      = f.select :priority, options_for_select({'low'=> 0, 'medium'=>1, 'high'=>2}, @task.priority),{}, {required: 'true', autofocus: 'true', class: 'form-control'}            
    .field.form-group.col-sm-6
      = f.label :created_date
      = f.text_field :created_date, class:'form-control datepicker',readonly: true
    .field.form-group.col-sm-6
      = f.label :due_date
      = f.text_field :due_date, class:'form-control datepicker',readonly: true
    .actions.from-group.col-sm-12.btn
      .col-sm-2
        = f.submit 'Save', class: 'form-control btn btn-inverse'
      .col-sm-2
        = link_to 'Back', tasks_path, class: 'form-control btn btn-reverse'

app/views/tasks/_form.html.haml
.container
.row
.col-md-12.form
  = form_for @task do |f|
    - if @task.errors.any?
      #error_explanation
        %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
        %ul
          - @task.errors.full_messages.each do |message|
            %li= message

    .field.form-group.col-sm-6
      = f.label :name
      = f.text_field :name,class:'form-control'
    .field.form-group.col-sm-6
      = f.label :description
      = f.text_area :description,class:'form-control'
    .field.form-group.col-sm-6
      = f.label :status
      = f.select :status, options_for_select([['undone', 0], ['done', 1]], params[:status]),{prompt: true, selected: 'undone'}, {required: 'true', autofocus: 'true', class: 'form-control'}
    .field.form-group.col-sm-6
      = f.label :priority
      = f.select :priority, options_for_select({'low'=> 0, 'medium'=>1, 'high'=>2}, @task.priority),{}, {required: 'true', autofocus: 'true', class: 'form-control'}      
    .field.form-group.col-sm-6
      = f.label :created_date
      = f.text_field :created_date, class:'form-control datepicker'
    .field.form-group.col-sm-6
      = f.label :due_date
      = f.text_field :due_date, class:'form-control datepicker'
    .field.from-group.col-sm-6
      = f.label :user_id
      = f.select :user_id, options_from_collection_for_select(@user,'id','email', f.object.user_id),{prompt: true, selected: @task.user_id}, {required: 'true', autofocus: 'true', class: 'form-control sel'}
    .actions.from-group.col-sm-12.btn
      .col-sm-2
        = f.submit 'Save', class: 'form-control btn btn-inverse'
      .col-sm-2
        = link_to 'Back', tasks_path, class: 'form-control btn btn-reverse'

app/views/tasks/confirm.html.haml
%h1 Confirm Task

= render 'confirmform'

app/views/tasks/edit.html.haml
%h1 Edit Task

= render 'form'

app/views/tasks/index.html.haml
%h1 MyTask

= link_to 'New Task', new_task_path,class: 'btn btn-inverse btn-mar'
.container
  .row
    .col-md-12.filter
      %h3 FILTER
      .col-md-4
        = form_tag  tasks_path, method: "get" do
          = label_tag :status
          = select_tag :status, options_for_select([['',nil],['undone', 0], ['done', 1]], params[:status]), class:'form-control'
          = submit_tag "Filter", name: nil, class:' btn btn-default col-md-2 btn-mar'
      .col-md-4
        = form_tag  tasks_path, method: "get" do
          = label_tag :priority
          = select_tag :priority, options_for_select([['',nil],['low', 0], ['medium', 1],['hight',2]], params[:priority]), class:'form-control'
          = submit_tag "Filter", name: nil, class:' btn btn-default col-md-2 btn-mar'
      .col-md-4
        = form_tag tasks_path, method: "get" do
          = label_tag :due_date
          = text_field_tag :due_date, nil, class:'form-control datepicker'
          = submit_tag "Filter", name: nil, class:' btn btn-default col-md-2 btn-mar'
.container
  .row
  %table.table.table-bordered.table-hover.table-responsive
    %thead
      %tr 
        %th Name
        %th Description
        %th Status
        %th Priority
        %th Created at
        %th Due date 
        %th
        %th

    %tbody
      - @task.each do |task|
        %tr
          %td= task.name
          %td= task.description
          - if (task.status == 0)
            %td= link_to 'Undone', confirm_path(task), class: 'btn btn-default btn-tab'
          - if (task.status == 1)
            %td 
              %button.btn.btn-success.btn-tab{:type => "button"} Done
          - if (task.priority == 0)
            %td
              %button.btn.btn-primary.btn-tab{:type => "button"} Low
          - if (task.priority == 1)
            %td
              %button.btn.btn-warning.btn-tab{:type => "button"} Medium
          - if (task.priority == 2)
            %td
              %button.btn.btn-danger.btn-tab{:type => "button" } High
          %td= task.created_at.strftime("%F")
          %td= task.due_date.strftime("%F")
          - if (task.created_by == current_user.id)
            %td= link_to 'Edit', edit_task_path(task), class: 'btn btn-inverse btn-tab'
            %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-reverse btn-tab'
          - else  
            %td= ''
            %td= ''
          

app/views/tasks/new.html.haml
%h1 New Task

= render 'form'

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Description:
  = @task.description
%p
  %b Status:
  -if (@task.status == 0)
    = 'undone'
  -if (@task.status == 1)
    = 'done'
%p
  %b Created at:
  = @task.created_date
%p
  %b Due date:
  = @task.due_date
%p
  %b Priority:
  -if (@task.priority == 0)
    = 'low'
  -if (@task.priority == 1)
    = 'medium'
  -if (@task.priority == 2)
    = 'high'
%br
  = link_to 'Back', tasks_path

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml